Add alt in insertFigure
openstax-poland/cnx-designer pull request #118
Opened 2021-02-03 09:25 UTC by jarosik10

for: https://github.com/openstax-poland/cnx-designer/issues/116

2021-02-03 13:07 UTC, aiwenar requested changes
This change will only affect media elements created using `insertFigure`, but not ones created using `insertSubfigure` or manually via `Transforms.insertNodes`. It also won't ensure that all `Media` elements have alt texts, as `AltText` can still be removed after `Media` is created. 

It will also insert a second `AltText` if `media` argument to `insertFigure` already is a `Media` node with an `AltText` child.

Finally, requiring that all `Media` elements have `AltText` is part of document schema, which in Slate is enforced with normalizations. Please at this as a normalization in `src/normalizations/figure.ts`.

However, it might still be worth including `AltText` in newly created figures as it would then save one round of normalizations. In such case, please do it in `itemToChildren`.

2021-02-04 11:19 UTC, jarosik10 commented
@aiwenar Do we want all `Media` elements include `alt`, even audio? This normalization makes some test fail right now.

2021-02-04 14:05 UTC, aiwenar requested changes
> Do we want all `Media` elements include `alt`, even audio? This normalization makes some test fail right now.

If you look at [CNXML documentation for the `<media>` element](https://legacy.cnx.org/eip-help/media) you'll notice that the `alt` attribute is required, regardless of what media elements there are. I'd say that tests need to be adjusted.

2021-02-04 14:05 UTC, aiwenar commented on src/normalize/figure.ts
> +            Transforms.insertNodes(editor, alt, { at: [...path, node.children.length] })
```suggestion
            Transforms.insertNodes(editor, {
                type: 'media_alt',
                children: [{ text: '' }]
            }, { at: [...path, node.children.length] })
```

2021-02-04 14:05 UTC, aiwenar commented on src/transforms/figure.ts
> +        if (!AltText.isAltText(media.children[media.children.length - 1])) {
```suggestion
        if (!media.children.some(AltText.isAltText)) {
```

You shouldn't assume that existing `AltText` element will be last.

2021-02-09 15:45 UTC, aiwenar approved these changes
Looks good now. Please squash commits and it will be good to merge.

2021-02-10 08:55 UTC, jarosik10 commented
@aiwenar should I fix the tests inside this PR as well? And how exactly should the commits be squashed?

2021-02-10 14:50 UTC, aiwenar commented
> should I fix the tests inside this PR as well?

Yes, these are all failures related to this PR.

> And how exactly should the commits be squashed?

Such that the commit history reflects evolution of the project, rather than the back and forth between the committer and the reviewer.

2021-02-16 08:31 UTC, PiotrKozlowski commented
@aiwenar Prośba o merge też tego pr jeżeli wszystko się zgadza

2021-02-16 09:37 UTC, merged