pressing enter when cursor is at the end of the line in caption does …
openstax-poland/cnx-designer pull request #154
Opened 2021-11-30 14:14 UTC by OneByteTwoByte

…not make an error

2021-12-01 09:00 UTC, aiwenar requested changes

2021-12-01 09:00 UTC, aiwenar commented on src/handlers.ts
> +                Editor.insertText(editor, '\n')
A new line (`'\n'`) in this context will be normalized to a space, so this change effectively makes enter and space equivalent.

What the original code intended to do, when an enter is pressed inside a caption, is split the caption in two and move the part after the cursor out of the figure. The important part is moving out of figure, not the visual appearance of a break.

2021-12-07 13:41 UTC, aiwenar approved these changes
Looks good now.

In future please only force-push once a PR has been approved.

2021-12-07 13:41 UTC, aiwenar commented on src/handlers.ts
> -
This line was unnecessarily removed.

2021-12-07 13:41 UTC, aiwenar commented
It might also be good to add a test case that would crash without this fix.

2021-12-10 12:03 UTC, OneByteTwoByte commented
I have added test for this issue. It crashes without this fix. Is this ok?

2021-12-10 12:24 UTC, aiwenar approved these changes
> I have added test for this issue. It crashes without this fix. Is this ok?

That was the issue, wasn't it :wink: 

Aside from that, please rebase this PR such that both the fix and test are in a single commit, and it will be good to merge.

2021-12-14 08:50 UTC, jarosik10 approved these changes

2021-12-14 08:53 UTC, merged